(define (problem task)
(:domain picknplacepileclass)
(:objects
    table twlrag waffle1 waffle2 checkered1 checkered2 checkered3 linrag - garment
    long short - grasp
    placevert placediag placerot - placing
    grws rotws - workspace
    grasped placed notgrasped lifted - state
    home high_pose else drag_pose - position
    flat a b c - defclass
)
(:init
    (garment_at twlrag rotws)
    (garment_at waffle1 rotws)
    (garment_at waffle2 rotws)
    (garment_at checkered1 rotws)
    (garment_at checkered2 rotws)
    (garment_at checkered3 rotws)
    (garment_at linrag rotws)

    (at_pose twlrag long)
    (at_pose waffle1 long)
    (at_pose waffle2 long)
    (at_pose checkered1 short)
    (at_pose checkered2 short)
    (at_pose checkered3 long)
    (at_pose linrag long)

    (garment_state table placed)
    (garment_state twlrag notgrasped)
    (garment_state waffle1 notgrasped)
    (garment_state waffle2 notgrasped)
    (garment_state checkered1 notgrasped)
    (garment_state checkered2 notgrasped)
    (garment_state checkered3 notgrasped)
    (garment_state linrag notgrasped)


    (not (corners_pos_known twlrag))
    (not (corners_pos_known waffle1))
    (not (corners_pos_known waffle2))
    (not (corners_pos_known checkered1))
    (not (corners_pos_known checkered2))
    (not (corners_pos_known checkered3))
    (not (corners_pos_known linrag))

    (robot_at else)

    (robot_empty)

    (known_obj twlrag)
    (not (known_obj waffle1))
    (not (known_obj waffle2))
    (not (known_obj checkered1))
    (not (known_obj checkered2))
    (not (known_obj checkered3))
    (not (known_obj linrag))

    (defstate twlrag flat)
    (defstate waffle1 flat)
    (defstate waffle2 flat)
    (defstate checkered1 flat)
    (defstate checkered2 flat)
    (defstate checkered3 flat)
    (defstate linrag flat)

    (obj_grasp_class waffle2 short b)
    (obj_grasp_class waffle2 long c)
    (obj_grasp_class checkered3 short b)
    (obj_grasp_class checkered3 long c)
    (obj_grasp_class checkered1 short B)
    (obj_grasp_class checkered1 long C)
    (obj_grasp_class checkered2 short B)
    (obj_grasp_class checkered2 long C)
    (obj_grasp_class twlrag short A)
    (obj_grasp_class twlrag long A)
    (obj_grasp_class waffle1 short B)
    (obj_grasp_class waffle1 long C)
    (obj_grasp_class linrag short B)
    (obj_grasp_class linrag long C)



    (= (time_cost) 0)

    (= (place_qual) 0)

    (= (place_succ twlrag a placevert) 17)
    (= (place_succ twlrag a placediag) 1)
    (= (place_succ twlrag a placerot) 1)
    (= (place_succ twlrag b placevert) 8)
    (= (place_succ twlrag b placediag) 22)
    (= (place_succ twlrag b placerot) 6)
    (= (place_succ twlrag c placevert) 30)
    (= (place_succ twlrag c placediag) 25)
    (= (place_succ twlrag c placerot) 6)
    (= (place_succ waffle1 a placevert) 7)
    (= (place_succ waffle1 a placediag) 3)
    (= (place_succ waffle1 a placerot) 4)
    (= (place_succ waffle1 b placevert) 30)
    (= (place_succ waffle1 b placediag) 14)
    (= (place_succ waffle1 b placerot) 9)
    (= (place_succ waffle1 c placevert) 30)
    (= (place_succ waffle1 c placediag) 30)
    (= (place_succ waffle1 c placerot) 30)
    (= (place_succ waffle2 a placevert) 7)
    (= (place_succ waffle2 a placediag) 3)
    (= (place_succ waffle2 a placerot) 4)
    (= (place_succ waffle2 b placevert) 30)
    (= (place_succ waffle2 b placediag) 14)
    (= (place_succ waffle2 b placerot) 9)
    (= (place_succ waffle2 c placevert) 30)
    (= (place_succ waffle2 c placediag) 30)
    (= (place_succ waffle2 c placerot) 30)
    (= (place_succ checkered1 a placevert) 7)
    (= (place_succ checkered1 a placediag) 3)
    (= (place_succ checkered1 a placerot) 4)
    (= (place_succ checkered1 b placevert) 30)
    (= (place_succ checkered1 b placediag) 14)
    (= (place_succ checkered1 b placerot) 9)
    (= (place_succ checkered1 c placevert) 30)
    (= (place_succ checkered1 c placediag) 30)
    (= (place_succ checkered1 c placerot) 30)
    (= (place_succ checkered2 a placevert) 7)
    (= (place_succ checkered2 a placediag) 3)
    (= (place_succ checkered2 a placerot) 4)
    (= (place_succ checkered2 b placevert) 30)
    (= (place_succ checkered2 b placediag) 14)
    (= (place_succ checkered2 b placerot) 9)
    (= (place_succ checkered2 c placevert) 30)
    (= (place_succ checkered2 c placediag) 30)
    (= (place_succ checkered2 c placerot) 30)
    (= (place_succ linrag a placevert) 7)
    (= (place_succ linrag a placediag) 3)
    (= (place_succ linrag a placerot) 4)
    (= (place_succ linrag b placevert) 30)
    (= (place_succ linrag b placediag) 14)
    (= (place_succ linrag b placerot) 9)
    (= (place_succ linrag c placevert) 30)
    (= (place_succ linrag c placediag) 30)
    (= (place_succ linrag c placerot) 30)

)
(:goal (and
    (on twlrag table)
    (on waffle1 twlrag)
    (on checkered1 waffle1)
    (on checkered2 checkered1)
    (on linrag checkered2)
))
(:metric minimize (+ (time_cost) (place_qual)))
)
