(define (problem task)
(:domain picknplacepileclass)
(:objects
    table towel waffle1 waffle2 checkered1 checkered2 checkered3 linen - garment
    long short - grasp
    placevert placediag placerot - placing
    grws rotws - workspace
    grasped placed notgrasped lifted - state
    home high_pose else drag_pose - position
    flat a b c - defclass
)
(:init
    (garment_at towel rotws)
    (garment_at waffle1 rotws)
    (garment_at waffle2 rotws)
    (garment_at checkered1 rotws)
    (garment_at checkered2 rotws)
    (garment_at checkered3 rotws)
    (garment_at linen rotws)

    (at_pose towel long)
    (at_pose waffle1 long)
    (at_pose waffle2 long)
    (at_pose checkered1 short)
    (at_pose checkered2 short)
    (at_pose checkered3 long)
    (at_pose linen long)

    (garment_state table placed)
    (garment_state towel notgrasped)
    (garment_state waffle1 notgrasped)
    (garment_state waffle2 notgrasped)
    (garment_state checkered1 notgrasped)
    (garment_state checkered2 notgrasped)
    (garment_state checkered3 notgrasped)
    (garment_state linen notgrasped)


    (not (corners_pos_known towel))
    (not (corners_pos_known waffle1))
    (not (corners_pos_known waffle2))
    (not (corners_pos_known checkered1))
    (not (corners_pos_known checkered2))
    (not (corners_pos_known checkered3))
    (not (corners_pos_known linen))

    (robot_at else)

    (robot_empty)

    (known_obj towel)
    (not (known_obj waffle1))
    (not (known_obj waffle2))
    (not (known_obj checkered1))
    (not (known_obj checkered2))
    (not (known_obj checkered3))
    (not (known_obj linen))

    (defstate towel flat)
    (defstate waffle1 flat)
    (defstate waffle2 flat)
    (defstate checkered1 flat)
    (defstate checkered2 flat)
    (defstate checkered3 flat)
    (defstate linen flat)

    (obj_grasp_class checkered3 short b)
    (obj_grasp_class checkered3 long c)
    (obj_grasp_class linen short b)
    (obj_grasp_class linen long c)
    (obj_grasp_class towel short A)
    (obj_grasp_class towel long A)
    (obj_grasp_class checkered1 short B)
    (obj_grasp_class checkered1 long C)
    (obj_grasp_class checkered2 short B)
    (obj_grasp_class checkered2 long C)
    (obj_grasp_class waffle1 short B)
    (obj_grasp_class waffle1 long C)
    (obj_grasp_class waffle2 short B)
    (obj_grasp_class waffle2 long C)



    (= (time_cost) 0)

    (= (place_qual) 0)

    (= (place_succ towel a placevert) 1)
    (= (place_succ towel a placediag) 1)
    (= (place_succ towel a placerot) 1)
    (= (place_succ towel b placevert) 1)
    (= (place_succ towel b placediag) 1)
    (= (place_succ towel b placerot) 1)
    (= (place_succ towel c placevert) 1)
    (= (place_succ towel c placediag) 1)
    (= (place_succ towel c placerot) 1)
    (= (place_succ waffle1 a placevert) 1)
    (= (place_succ waffle1 a placediag) 1)
    (= (place_succ waffle1 a placerot) 1)
    (= (place_succ waffle1 b placevert) 1)
    (= (place_succ waffle1 b placediag) 1)
    (= (place_succ waffle1 b placerot) 1)
    (= (place_succ waffle1 c placevert) 1)
    (= (place_succ waffle1 c placediag) 1)
    (= (place_succ waffle1 c placerot) 1)
    (= (place_succ waffle2 a placevert) 1)
    (= (place_succ waffle2 a placediag) 1)
    (= (place_succ waffle2 a placerot) 1)
    (= (place_succ waffle2 b placevert) 1)
    (= (place_succ waffle2 b placediag) 1)
    (= (place_succ waffle2 b placerot) 1)
    (= (place_succ waffle2 c placevert) 1)
    (= (place_succ waffle2 c placediag) 1)
    (= (place_succ waffle2 c placerot) 1)
    (= (place_succ checkered1 a placevert) 1)
    (= (place_succ checkered1 a placediag) 1)
    (= (place_succ checkered1 a placerot) 1)
    (= (place_succ checkered1 b placevert) 1)
    (= (place_succ checkered1 b placediag) 1)
    (= (place_succ checkered1 b placerot) 1)
    (= (place_succ checkered1 c placevert) 1)
    (= (place_succ checkered1 c placediag) 1)
    (= (place_succ checkered1 c placerot) 1)
    (= (place_succ checkered2 a placevert) 1)
    (= (place_succ checkered2 a placediag) 1)
    (= (place_succ checkered2 a placerot) 1)
    (= (place_succ checkered2 b placevert) 1)
    (= (place_succ checkered2 b placediag) 1)
    (= (place_succ checkered2 b placerot) 1)
    (= (place_succ checkered2 c placevert) 1)
    (= (place_succ checkered2 c placediag) 1)
    (= (place_succ checkered2 c placerot) 1)
    (= (place_succ checkered3 a placevert) 1)
    (= (place_succ checkered3 a placediag) 1)
    (= (place_succ checkered3 a placerot) 1)
    (= (place_succ checkered3 b placevert) 1)
    (= (place_succ checkered3 b placediag) 1)
    (= (place_succ checkered3 b placerot) 1)
    (= (place_succ checkered3 c placevert) 1)
    (= (place_succ checkered3 c placediag) 1)
    (= (place_succ checkered3 c placerot) 1)
    (= (place_succ linen a placevert) 1)
    (= (place_succ linen a placediag) 1)
    (= (place_succ linen a placerot) 1)
    (= (place_succ linen b placevert) 1)
    (= (place_succ linen b placediag) 1)
    (= (place_succ linen b placerot) 1)
    (= (place_succ linen c placevert) 1)
    (= (place_succ linen c placediag) 1)
    (= (place_succ linen c placerot) 1)

)
(:goal (and
    (on towel table)
    (on checkered1 towel)
    (on checkered2 checkered1)
    (on waffle1 checkered2)
    (on waffle2 waffle1)
))
(:metric minimize (+ (time_cost) (place_qual)))
)
