play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]

  motions:

    final_position:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_right_finger_joint', 'gripper_left_finger_joint']
      points:
      - positions: [0.1, 1.632, -1.5, -2.47, 1.65, -2.05, 0.84, -1.66, 0.007, 0.007]
        time_from_start: 0.0
      meta:
        name: Final Position
        usage: demo
        description: 'Final Position'
