play_motion:
  controllers: [arm_controller, head_controller, torso_controller, gripper_controller]

  motions:
    give_garment:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'gripper_right_finger_joint', 'gripper_left_finger_joint']
      points:
      - positions: [0.35, 2.1, -0.07, -2.3, 1.35, -0.608, -0.09, -1.27, 0.007, 0.007]
        time_from_start: 1.0
      meta:
        name: Give Garment
        usage: demo
        description: 'Give Garment'
