#include "hddl_parser.h" // designed by user
#include "hddl_parser.tab.hpp" // automatically generated by bison

// constructor
HDDLParser::HDDLParser() : parsing_ok_(true) {}

int HDDLParser::parse(const std::string &file_path)
{
    domain_.domain_file_path_ = file_path;
    location_.initialize(&domain_.domain_file_path_);
    scan_begin();
    yy::parser hddl_parser(*this);
    hddl_parser.set_debug_level(false);
    int res = hddl_parser.parse();
    scan_end();

    return res;
}

bool HDDLParser::parsing_ok()
{
    return parsing_ok_;
}
